// frontend-react/src/components/TelaUsuario/Inicial.jsx
import './Inicial.css';
import { useNavigate } from 'react-router-dom';

const Inicial = () => {
    const navigate = useNavigate();

    return (
        <div className='pagina-inicial-container'>
            <h1>
                Gerenciando e organizando as suas tarefas
            </h1>
            <p>
                Faça login ou cadastre-se para começar a organizar suas atividades conosco!!
            </p>
            <div className='botoes'>
                <button className='btn' onClick={() => navigate('/login')}>
                    Login
                </button>
                <button className='btn' onClick={() => navigate('/cadastro')}>
                    Cadastro
                </button>
            </div>
        </div>
    );
}

export default Inicial;

// frontend-vue/src/components/usuario/inicial.vue
<script setup>
import { RouterLink } from 'vue-router'
</script>

<template>
    <div class="pagina-inicial-container">
        <h1>Gerenciando e organizando as suas tarefas</h1>
        <p>Faça login ou cadastre-se para começar a organizar suas atividades conosco!</p>
        <div class="botoes">
            <RouterLink to="/login">
                <button class="btn">Login</button>
            </RouterLink>
            <RouterLink to="/cadastro">
                <button class="btn">Cadastro</button>
            </RouterLink>
        </div>
    </div>
</template>

<style scoped>
@import '../../assets/css/inicial.css';
</style>
