// frontend-react/src/components/TelaUsuario/Login.jsx
import './Login.css';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { useState } from 'react';

const Login = () => {
    const navigate = useNavigate();
    const [email, setEmail] = useState('');
    const [senha, setSenha] = useState('');

    const handleLogin = (e) => {
        e.preventDefault();

        axios.post('http://localhost:8082/gerenciador-de-tarefas/api/auth/login', { email, senha })
            .then((response) => {
                const data = response.data;

                if (data.token) {
                    localStorage.setItem('token', data.token);  
                }

                if(data.usuario) {
                    localStorage.setItem('usuario', JSON.stringify(data.usuario));

                }
                navigate('/novaTarefa');
            })
            .catch((error) => {
                console.error('Erro no login:', error);
                alert('Email ou senha inválidos.');
            }
        );
    };

    return (
        <div className="pagina-login-container">
            <div className="conteudo">
                <h1>Login</h1>

                <form className="form-group" onSubmit={handleLogin}>
                    <input
                        type="text"
                        placeholder="E-mail"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        required
                    />
                    <input
                        type="password"
                        placeholder="Senha"
                        value={senha}
                        onChange={(e) => setSenha(e.target.value)}
                        required
                    />
                    <div className="form-options">
                        <a href="#">Esqueceu a senha?</a>
                        <button type="submit" className="btn-submit">Entrar</button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default Login;

// frontend-vue/src/components/usuario/login.vue
<script setup>
import { ref } from "vue";
import axios from "axios";
import { useRouter } from "vue-router";
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { faEye, faEyeSlash } from '@fortawesome/free-solid-svg-icons'

const email = ref("");
const senha = ref("");

const router = useRouter();

const handleLogin = async () => {
    try {
        const response = await axios.post(
            "http://localhost:8082/gerenciador-de-tarefas/api/auth/login",
            {email: email.value, senha: senha.value}
        );

        const data = response.data;

        if (data.token) {
            localStorage.setItem("token", data.token);
        }

        if (data.usuario) {
            localStorage.setItem("usuario", JSON.stringify(data.usuario));
        }

        router.push("/novaTarefa");
    } catch (error) {
        console.log("Erro no login:", error);
        alert("Email ou senha inváidos");
    }
};
</script>
<template>
    <div class="pagina-login-container">
        <div class="conteudo">
            <h1>Login</h1>
            <form class="form-group" @submit.prevent="handleLogin">
                <input
                    type="text"
                    placeholder="E-mail"
                    v-model="email"
                    required
                />
                
                <input
                    type="password"
                    placeholder="senha"
                    v-model="senha"
                    required
                />
                <div class="form-options">
                    <button type="submit" class="btn-submit">Entrar</button>
                </div>
            </form>
        </div>
    </div>
</template>

<style scoped>
@import '../../assets/css/login.css';
</style>
